### ISSUE TITLE
incorrect results?

### ISSUE THREAD

**Issue by jpfry327** [btackett3/ModalConsistencyChecker#2]
Saw this on Daily Nous and decided to check it out.  But a few valid formulas don't seem to be coming up as valid.  I tested (p&(p>q))>q and N(p>q)>(Np>Nq), both coming out as invalid. E.g. for N(p>q)>(Np>Nq), it gives the correct polish notation but says it's false in a model with a two worlds, both with p, ~q. (why the extra world?) That makes the antecedent false and hence the whole thing is true. Is my input wrong?

**Comment by btackett3** [comment]
Hi. Thanks for catching those. Your inputs look fine, and I can replicate
both problems.

For the modal one, the model it is returning has a non-atomic formula in
it. So, it must be stopping too soon.

For the non-modal one, the model contains things with syntactic errors.

So, both are bugs in the program, not errors on your part. I will look into
fixing them when I am not on a phone.

Thanks,
Brian

**Comment by btackett3** [comment]
N(p>q)>(Np>Nq) should work on the site now.  

Will work on (p&(p>q))>q next.  

(Then catch github up to the site's files).

**Comment by btackett3** [comment]
Both of your cases should work now.  Let me know if you run into any other bugs.
